import { MusicFrom, MusicInfo, PlayListType } from '../model/MusicData'

// 播放器当前播放列表
const MusicListData: MusicInfo[] = [
    {
        id: "0",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "2",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "3",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "4",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "5",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },


    {
        id: "6",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "7",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "8",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "9",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "10",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "11",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "12",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "13",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "14",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "15",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "16",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "17",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "18",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },


    {
        id: "19",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "20",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "21",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "22",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "23",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "24",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "25",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "26",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "27",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "28",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "29",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "30",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "31",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },


    {
        id: "32",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "33",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "34",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "35",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "36",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "37",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "38",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "39",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "40",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "41",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "42",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "43",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "44",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "45",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "46",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "47",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "48",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "49",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "50",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "51",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "52",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "53",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "54",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "55",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "56",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "57",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "58",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "59",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "60",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },
]

export { MusicListData }
