import { MusicFrom, MusicInfo, PlayListType } from '../model/MusicData'

// 播放器当前播放列表
const MusicListData: MusicInfo[] = [
    {
        id: "208902",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "208902",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1441758494",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "2684595357",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "208902",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1441758494",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "2684595357",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "208902",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1441758494",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1441758494",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "2684595357",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 2,
        playList: PlayListType.NETEASE_RAND
    },
    {
        id: "208902",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "04:14",
        lrc: "",
        pay: true,
        where: MusicFrom.NetEase,
        index: 0,
        playList: PlayListType.NETEASE_RAND
    },

    {
        id: "1441758494",
        name: "谁(Live)",
        singer: "廖俊涛",
        url: "https://api.ilingku.com/int/v1/rand_netease?sort=热歌榜",
        pic: "https://api.52vmy.cn/api/avath/qq?qq=1423443710",
        duration: "03:22",
        lrc: "",
        pay: false,
        where: MusicFrom.NetEase,
        index: 1,
        playList: PlayListType.NETEASE_RAND
    },

]

export { MusicListData }
