export class RouterUrlConstants {
    static readonly ABOUT = "pages/AboutPage";
    static readonly EXPORT_PLAYLIST = "pages/ExportPlayListPage";
    static readonly HOME = "pages/HomePage";
    static readonly PLAY_QUEUE = "pages/PlayQueuePage";
    static readonly LOGIN = "pages/LoginPage";
    static readonly PLAY = "pages/PlayPage";
    static readonly PROFILE = "pages/ProfilePage";
    static readonly RECENT = "pages/RecentPlayPage"
    static readonly REGISTER = "pages/RegisterPage";
    static readonly RETRIEVE_PASSWD = "pages/RetrievePasswdPage";
    static readonly SEARCH = "pages/SearchPage";
    static readonly SETTING = "pages/SettingPage";
}
