export class StyleConstants {
  static readonly FULL_WIDTH: string = '100%';

  static readonly FULL_HEIGHT: string = '100%';

  static readonly TRANSLATE_X: number = 10;

  /**
   * Translate value of the number of playbacks.
   */
  static readonly TRANSLATE_Y: string = '-100%';

  /**
   * Translate value of the player area on the bottom.
   */
  static readonly TRANSLATE_PLAYER_Y: string = '-50vp';
}